version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/Matsushin/go-ecs-ecr
      - checkout
      - run:
          name: "go get"
          command: |
            go get -v -t -d ./...
      - run:
          name: "go test"
          command: |
            go test -v ./...