version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: ~/go/src/github.com/Matsushin/go-ecs-ecr
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Build
          command: |
            docker build -t 518965002790.dkr.ecr.ap-northeast-1.amazonaws.com/go-sample-webapp:$CIRCLE_SHA1 .
      - run:
          name: "go get"
          command: |
            go get -v -t -d ./...
      - run:
          name: "go test"
          command: |
            go test -v ./...