version: 2
jobs:
  ecr-deploy:
    working_directory: ~/go/src/github.com/Matsushin/go-ecs-ecr
    docker:
      - image: circleci/python:2.7-node-browsers
        environment:
          AWS_ID: '518965002790'
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install awscli
      - run: $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - run:
          name: Build ECR API
          command: |
            docker build -f ./Dockerfile  -t go-sample-webapp .
      - run:
          ame: TAG ECR API
          command: |
            docker tag go-sample-webapp ${AWS_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/go-sample-webapp:latest
      - run:
          name: Deploy
          command: |
            export AWS_DEFAULT_REGION="ap-northeast-1"
            export ECS_TASK_FAMILY_NAME="sample-webapp-task${TARGET}"
            export ECS_CONTAINER_DEFINITION_NAME="sample-webapp-containerX${TARGET}"
            export EXECUTION_ROLE_ARN="arn:aws:iam::$AWS_ID:role/ecsTaskExecutionRole"
            # bash ./deploy.sh
            bash ./deploy2.sh

# Workflows
workflows:
  version: 2
  ecr-deploy:
    jobs:
      - ecr-deploy:
          filters:
            branches:
              only:
                - master